import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useState, useRef } from "react";

const Home: NextPage = () => {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [id, setId] = useState("");

  const nameInputRef = React.useRef<HTMLInputElement>(null);
  const emailInputRef = React.useRef<HTMLInputElement>(null);
  const idInputRef = React.useRef<HTMLInputElement>(null);

  const handleGetUsers = () => {
    handleClick();
    fetch("api/read")
      .then((res) => res.json())
      .then((res) => {
        console.log("got these users: ", res);
      });
  };

  const handleCreateUsers = () => {
    console.log(
      "create a user with the name of:",
      name,
      "and email of:",
      email
    );

    const data = {
      name: name,
      email: email,
    };

    fetch("api/create", {
      method: "POST",
      body: JSON.stringify(data),
    })
      .then((res) => res.json())
      .then((res) => {
        console.log("this user created: ", res);
      });
  };

  const handleDeleteUser = () => {
    console.log("delete user with id of:", id);
    const data = {
      id: id,
    };
    fetch("api/delete", {
      method: "DELETE",
      body: JSON.stringify(data),
    })
      .then((res) => res.json())
      .then((res) => {
        console.log("deleted this user: ", res);
      });
  };

  const handleInput = () => {
    const nameInput: string = nameInputRef.current?.value!;
    setName(nameInput);

    const emailInput: string = emailInputRef.current?.value!;
    setEmail(emailInput);

    const idInput: string = idInputRef.current?.value!;
    setId(idInput);
  };

  const handleClick = () => {
    console.log(nameInputRef.current?.value);
    console.log(emailInputRef.current?.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="input-container">
          Name: <input ref={nameInputRef} onChange={handleInput} />
        </div>
        <div className="input-container">
          Email: <input ref={emailInputRef} onChange={handleInput} />
        </div>
        <div className="input-container">
          Id: <input ref={idInputRef} onChange={handleInput} />
        </div>
        <button onClick={handleGetUsers}>Get Users</button>{" "}
        <button onClick={handleCreateUsers}>Create User</button>{" "}
        <button onClick={handleDeleteUser}>Delete User</button>{" "}
      </main>
    </div>
  );
};

export default Home;
